# Generated by Django 5.2.7 on 2026-01-09 00:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Development',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Desarrollo')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('location', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('state', models.CharField(max_length=100, verbose_name='Estado')),
                ('total_units', models.IntegerField(default=0, verbose_name='Total de Unidades')),
                ('available_units', models.IntegerField(default=0, verbose_name='Unidades Disponibles')),
                ('price_from', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Desde')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Desarrollo',
                'verbose_name_plural': 'Desarrollos',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DevelopmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='developments/', verbose_name='Imagen')),
                ('is_main', models.BooleanField(default=False, verbose_name='Imagen Principal')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('development', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='developments.development')),
            ],
            options={
                'verbose_name': 'Imagen de Desarrollo',
                'verbose_name_plural': 'Imágenes de Desarrollo',
                'ordering': ['order'],
            },
        ),
    ]
