# Generated by Django 5.2.7 on 2026-01-09 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='development',
            name='operation_type',
            field=models.CharField(choices=[('venta', 'Venta'), ('renta', 'Renta'), ('venta_renta', 'Venta y Renta')], default='venta', max_length=20, verbose_name='Tipo de Operación'),
        ),
    ]
