# Generated by Django 5.2.7 on 2026-01-09 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developments', '0002_development_operation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='development',
            name='google_maps_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL de Google Maps'),
        ),
    ]
