# Generated by Django 4.2.7 on 2026-01-22 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developments', '0003_development_google_maps_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developmentimage',
            options={'ordering': ['-is_main', 'order'], 'verbose_name': 'Imagen de Desarrollo', 'verbose_name_plural': 'Imágenes de Desarrollo'},
        ),
    ]
