# Generated by Django 5.2.7 on 2026-01-05 23:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre completo del contacto', max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=255, validators=[django.core.validators.EmailValidator()], verbose_name='Correo Electrónico')),
                ('phone', models.CharField(blank=True, help_text='Número de teléfono de contacto', max_length=20, verbose_name='Teléfono')),
                ('subject', models.CharField(help_text='Asunto del mensaje', max_length=200, verbose_name='Asunto')),
                ('message', models.TextField(help_text='Contenido del mensaje', verbose_name='Mensaje')),
                ('is_read', models.BooleanField(default=False, help_text='Marcar como leído', verbose_name='Leído')),
                ('is_responded', models.BooleanField(default=False, help_text='Marcar como respondido', verbose_name='Respondido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Respuesta')),
                ('property', models.ForeignKey(blank=True, help_text='Propiedad relacionada (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='properties.property', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='contact_con_created_263a6a_idx'), models.Index(fields=['is_read'], name='contact_con_is_read_e73e80_idx'), models.Index(fields=['property'], name='contact_con_propert_d58dfe_idx')],
            },
        ),
    ]
