# Generated by Django 4.2.7 on 2026-03-20 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def sync_legacy_status(apps, schema_editor):
    Contact = apps.get_model('contact', 'Contact')
    for item in Contact.objects.all().only('id', 'is_read', 'is_responded'):
        if item.is_responded:
            status = 'responded'
        elif item.is_read:
            status = 'in_progress'
        else:
            status = 'new'
        Contact.objects.filter(pk=item.pk).update(status=status)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Nota de contacto',
                'verbose_name_plural': 'Notas de contacto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contacts', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a'),
        ),
        migrations.AddField(
            model_name='contact',
            name='follow_up_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de seguimiento'),
        ),
        migrations.AddField(
            model_name='contact',
            name='internal_summary',
            field=models.TextField(blank=True, verbose_name='Resumen interno'),
        ),
        migrations.AddField(
            model_name='contact',
            name='priority',
            field=models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], db_index=True, default='medium', max_length=10, verbose_name='Prioridad'),
        ),
        migrations.AddField(
            model_name='contact',
            name='source',
            field=models.CharField(default='sitio_web', max_length=50, verbose_name='Origen'),
        ),
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('new', 'Nueva'), ('in_progress', 'En seguimiento'), ('responded', 'Respondida'), ('closed', 'Cerrada')], db_index=True, default='new', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['status'], name='contact_con_status_9a9384_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['priority'], name='contact_con_priorit_3b2dbc_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['assigned_to'], name='contact_con_assigne_aac917_idx'),
        ),
        migrations.RunPython(sync_legacy_status, migrations.RunPython.noop),
        migrations.AddField(
            model_name='contactnote',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_notes', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='contactnote',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='contact.contact', verbose_name='Solicitud'),
        ),
    ]
