# Generated by Django 5.2.7 on 2026-01-05 23:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la característica (ej: Piscina, Jardín, etc.)', max_length=100, unique=True, verbose_name='Nombre')),
                ('icon', models.CharField(blank=True, help_text='Clase de icono (FontAwesome, Material Icons, etc.)', max_length=50, verbose_name='Icono')),
            ],
            options={
                'verbose_name': 'Característica',
                'verbose_name_plural': 'Características',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título descriptivo de la propiedad', max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, help_text='URL amigable (se genera automáticamente)', max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(help_text='Descripción detallada de la propiedad', verbose_name='Descripción')),
                ('property_type', models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('terreno', 'Terreno'), ('local', 'Local Comercial'), ('oficina', 'Oficina'), ('bodega', 'Bodega'), ('rancho', 'Rancho'), ('otro', 'Otro')], default='casa', max_length=20, verbose_name='Tipo de Propiedad')),
                ('operation_type', models.CharField(choices=[('venta', 'Venta'), ('renta', 'Renta'), ('venta_renta', 'Venta o Renta')], default='venta', max_length=20, verbose_name='Tipo de Operación')),
                ('status', models.CharField(choices=[('disponible', 'Disponible'), ('vendida', 'Vendida'), ('rentada', 'Rentada'), ('reservada', 'Reservada'), ('no_disponible', 'No Disponible')], default='disponible', max_length=20, verbose_name='Estado')),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio en moneda local', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('currency', models.CharField(default='MXN', help_text='Código de moneda (MXN, USD, etc.)', max_length=3, verbose_name='Moneda')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('state', models.CharField(max_length=100, verbose_name='Estado/Provincia')),
                ('zip_code', models.CharField(blank=True, max_length=20, verbose_name='Código Postal')),
                ('country', models.CharField(default='México', max_length=100, verbose_name='País')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Coordenada GPS', max_digits=9, null=True, verbose_name='Latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Coordenada GPS', max_digits=9, null=True, verbose_name='Longitud')),
                ('bedrooms', models.PositiveIntegerField(default=0, help_text='Número de recámaras', verbose_name='Recámaras')),
                ('bathrooms', models.PositiveIntegerField(default=0, help_text='Número de baños', verbose_name='Baños')),
                ('parking_spaces', models.PositiveIntegerField(default=0, help_text='Número de espacios de estacionamiento', verbose_name='Estacionamientos')),
                ('area', models.DecimalField(decimal_places=2, help_text='Área total en metros cuadrados', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Área (m²)')),
                ('construction_area', models.DecimalField(blank=True, decimal_places=2, help_text='Área construida en metros cuadrados', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Área de Construcción (m²)')),
                ('lot_area', models.DecimalField(blank=True, decimal_places=2, help_text='Área del terreno en metros cuadrados', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Área de Terreno (m²)')),
                ('floors', models.PositiveIntegerField(default=1, help_text='Número de pisos o niveles', verbose_name='Niveles')),
                ('year_built', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de Construcción')),
                ('is_featured', models.BooleanField(default=False, help_text='Mostrar en la página principal', verbose_name='Destacada')),
                ('is_new', models.BooleanField(default=False, help_text='Marcar como propiedad nueva', verbose_name='Nueva')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Publicación')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='properties__created_9ef325_idx'), models.Index(fields=['status'], name='properties__status_6427a0_idx'), models.Index(fields=['property_type'], name='properties__propert_5c7790_idx'), models.Index(fields=['operation_type'], name='properties__operati_a40a1f_idx'), models.Index(fields=['city'], name='properties__city_74fa1a_idx'), models.Index(fields=['is_featured'], name='properties__is_feat_9e46bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Imagen de la propiedad', upload_to='properties/', verbose_name='Imagen')),
                ('is_main', models.BooleanField(default=False, help_text='Marcar como imagen principal', verbose_name='Imagen Principal')),
                ('alt_text', models.CharField(blank=True, help_text='Descripción de la imagen para accesibilidad', max_length=200, verbose_name='Texto Alternativo')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización', verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Imagen de Propiedad',
                'verbose_name_plural': 'Imágenes de Propiedades',
                'ordering': ['is_main', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyFeatureRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.propertyfeature', verbose_name='Característica')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='properties.property', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Característica de Propiedad',
                'verbose_name_plural': 'Características de Propiedades',
                'unique_together': {('property', 'feature')},
            },
        ),
    ]
