# Generated by Django 5.2.7 on 2026-01-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_fix_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='back_measure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Medida Fondo (m)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='front_measure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Medida Frente (m)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='half_bathrooms',
            field=models.PositiveIntegerField(default=0, help_text='Número de medios baños', verbose_name='Medios Baños'),
        ),
        migrations.AlterField(
            model_name='property',
            name='has_patio',
            field=models.BooleanField(default=False, verbose_name='Patio'),
        ),
    ]
