# Generated by Django 5.2.7 on 2026-01-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_back_measure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='google_maps_url',
            field=models.URLField(blank=True, help_text='Link de Google Maps de la ubicación', max_length=500, verbose_name='URL Google Maps'),
        ),
    ]
