# Generated by Django 4.2.7 on 2026-01-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_property_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del slide', max_length=200, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, help_text='Subtítulo o descripción breve', max_length=300, verbose_name='Subtítulo')),
                ('image', models.ImageField(help_text='Imagen del slide (recomendado: 1920x1080px)', upload_to='carousel/', verbose_name='Imagen')),
                ('link_url', models.URLField(blank=True, help_text='URL a la que redirigir al hacer clic (opcional)', null=True, verbose_name='URL de Enlace')),
                ('link_text', models.CharField(blank=True, default='Ver Más', help_text='Texto del botón de acción', max_length=100, verbose_name='Texto del Botón')),
                ('is_active', models.BooleanField(default=True, help_text='Mostrar este slide en el carrusel', verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización (menor número = primero)', verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Slide del Carrusel',
                'verbose_name_plural': 'Slides del Carrusel',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
