# Generated by Django 4.2.7 on 2026-03-20 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0008_property_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='exclusive_advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exclusive_properties', to=settings.AUTH_USER_MODEL, verbose_name='Asesor responsable de la exclusiva'),
        ),
        migrations.AddField(
            model_name='property',
            name='financing_options',
            field=models.JSONField(blank=True, default=list, help_text='Solo visible para administración/panel interno', verbose_name='Opciones de financiamiento'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_advisor_exclusive',
            field=models.BooleanField(default=False, help_text='Solo visible para administración/panel interno', verbose_name='Exclusiva de asesor'),
        ),
    ]
