# Generated by Django 5.2.7 on 2026-01-09 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Región')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='regions/', verbose_name='Imagen Principal')),
                ('highlights', models.TextField(help_text='Separar con comas', verbose_name='Puntos Destacados')),
                ('growth_level', models.CharField(choices=[('alto', 'Alto Crecimiento'), ('medio', 'Crecimiento Medio'), ('emergente', 'Zona Emergente')], default='medio', max_length=50)),
                ('order', models.IntegerField(default=0, verbose_name='Orden de Visualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
                'ordering': ['order', 'name'],
            },
        ),
    ]
